directories:
  output: release
  buildResources: build
  app: .
appId: com.siteweave.app
productName: SiteWeave
files:
  - filter:
      - dist-electron/**/*
      - dist/**/*
      - '!**/node_modules/**'
      - '!**/*.map'
      - '!**/*.d.ts'
      - '!**/win-unpacked/**'
      - '!**/.DS_Store'
      - '!**/Thumbs.db'
      - '!apps/**'
      - node_modules/electron-updater/**/*
win:
  target: nsis
  icon: build/icon.png
  verifyUpdateCodeSignature: false
mac:
  target:
    - dmg
    - zip
  category: public.app-category.productivity
  artifactName: ${productName}-${version}-${arch}.${ext}
appx:
  applicationId: com.siteweave.app
  displayName: SiteWeave
  publisherDisplayName: SiteWeave
  identityName: com.siteweave.app
  publisher: CN=SiteWeave
  backgroundColor: '#FFFFFF'
nsis:
  artifactName: ${productName}-Setup-${version}.${ext}
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish:
  provider: github
  owner: SiteWeave
  repo: SiteWeave
electronVersion: 38.3.0
